### ISSUE TITLE
Mutect2 tumor vs normal does not perform FILTERMUTECTCALLS step

### ISSUE THREAD

**Issue by msguixe** [nf-core/sarek#786] opened 2022-10-11 07:53 UTC
### Description of the bug

Hi,

I just realized that when running Mutect2, in tumor vs normal mode, it does not perform the FILTERMUTECTCALLS step. When I run it in single tumor mode, it does perform the filtering step. How can I add the filtering step with the sarek command?
Thanks,

### Command used and terminal output

```console
nextflow run nf-core/sarek -r 3.0.1 -profile singularity -c /workspace/datasets/sjd_seq/code/sarek/sarek_3.0.1.conf --input input_clones_vs_blood.csv --step variant_calling --tools 'strelka,ascat,manta,mutect2' --fasta /workspace/datasets/genomes/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fa --fasta_fai /workspace/datasets/genomes/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fa.fai --dict /workspace/datasets/genomes/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.dict --germline_resource /workspace/datasets/genomes/iGenomes/Homo_sapiens/GATK/GRCh38/Annotation/GermlineResource/gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only.vcf.gz --germline_resource_tbi /workspace/datasets/genomes/iGenomes/Homo_sapiens/GATK/GRCh38/Annotation/GermlineResource/gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only.vcf.gz.tbi
```

### Relevant files

patient,sex,status,sample,cram,crai
pt1,XX,1,AX4958,/workspace/datasets/sjd_seq/sarek_results/pt1/results/preprocessing/recalibrated/AX4958/AX4958.recal.cram,/workspace/datasets/sjd_seq/sarek_results/pt1/results/preprocessing/recalibrated/AX4958/AX4958.recal.cram.crai
pt1,XX,1,AX4961,/workspace/datasets/sjd_seq/sarek_results/pt1/results/preprocessing/recalibrated/AX4961/AX4961.recal.cram,/workspace/datasets/sjd_seq/sarek_results/pt1/results/preprocessing/recalibrated/AX4961/AX4961.recal.cram.crai
pt1,XX,0,AQ5174,/workspace/datasets/sjd_seq/platinum_results/20220809/pt1-t1-allsamples-t1/sarek_results/results/preprocessing/recalibrated/AQ5174/AQ5174.recal.cram,/workspace/datasets/sjd_seq/platinum_results/20220809/pt1-t1-allsamples-t1/sarek_results/results/preprocessing/recalibrated/AQ5174/AQ5174.recal.cram.crai

**Comment by FriederikeHanssen** [comment] 2022-10-11 10:40
Thanks for reporting. Taking a look

**Comment by FriederikeHanssen** [comment] 2022-10-11 10:49
Can you send me the log and ideally the terminal output? Was GETPILEUPSUMMARIES run?

**Comment by msguixe** [comment] 2022-10-11 12:15
[execution_trace_2022-10-10_11-39-31.txt.gz](https://github.com/nf-core/sarek/files/9754987/execution_trace_2022-10-10_11-39-31.txt.gz)
This is the execution trace file. It looks like the GETPILEUPSUMMARIES has been executed.

**Comment by FriederikeHanssen** [comment] 2022-10-11 13:38
I would need the .nextflow.log file please

**Comment by msguixe** [comment] 2022-10-11 13:46
[nextflow.log.gz](https://github.com/nf-core/sarek/files/9756440/nextflow.log.gz)

**Comment by FriederikeHanssen** [comment] 2022-11-03 15:24
Hi @msguixe ! Apologies for the delay, I was on vacation, but back now. I put it in my todo list for next week. I am afraid I am busy catching up with everything this week.

**Comment by FriederikeHanssen** [comment] 2022-11-07 22:35
Hey! So trying to track this down. On the previous release 3.0.2 it was run on the full size tests: https://tower.nf/orgs/nf-core/workspaces/AWSmegatests/watch/1VrKQdBhYDJB1G

https://nf-co.re/sarek/results#sarek/results-bcd7bf9cb98cddec27bb54fb47ee122c09388c02/somatic_test/variant_calling/mutect2/HCC1395T_vs_HCC1395N/

So I think a reference file might be missing from your command possibly

**Comment by FriederikeHanssen** [comment] 2022-11-07 22:55
😬 can't reproduce this. Can you try the same command with 3.0.2?

**Comment by msguixe** [comment] 2022-11-08 15:16
Hi Friederike,

It is currently running. I let you know about the output tomorrow!

Thanks,
Monica

**Comment by msguixe** [comment] 2022-11-09 09:52
The pipeline finished correctly, but still it doesn't give the filtered vcf :/
I'm not sure which ref file is missing...

**Comment by FriederikeHanssen** [comment] 2022-11-09 09:52
Hi! Ok thanks this good to know. then i know where I can start digging further

**Comment by FriederikeHanssen** [comment] 2022-11-09 21:07
OK so making progress on the debugging side: if I am not mistaken and overlooked it in your log files: LEARNREADORIENTATION is not run, is that correct?

**Comment by FriederikeHanssen** [comment] 2022-11-09 21:12
also would you mind testing dev as well with your setup?

**Comment by msguixe** [comment] 2022-11-10 15:43
Well I see that LEARNREADORIENTATION is also not performed...
This is a .command.sh from a MUTECT2 step:
```
#!/bin/bash -euo pipefail
gatk --java-options "-Xmx36g" Mutect2 \
    --input AQ5174.recal.cram --input AX4961.recal.cram \
    --output AX4961_vs_AQ5174.mutect2.chr22_10510001-10784643.vcf.gz \
    --reference GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fa \
    --panel-of-normals 1000g_pon.hg38.vcf.gz \
    --germline-resource gnomAD.r2.1.1.GRCh38.PASS.AC.AF.only.vcf.gz \
    --intervals chr22_10510001-10784643.bed \
    --tmp-dir . \
    --normal-sample null

cat <<-END_VERSIONS > versions.yml
"NFCORE_SAREK:SAREK:PAIR_VARIANT_CALLING:GATK_TUMOR_NORMAL_SOMATIC_VARIANT_CALLING:MUTECT2":
    gatk4: $(echo $(gatk --version 2>&1) | sed 's/^.*(GATK) v//; s/ .*$//')
END_VERSIONS

```

**Comment by FriederikeHanssen** [comment] 2022-11-10 19:24
Yes the that process is upstream of the filtering, and if that one isn't run then the filtering can't run because it is missing some inputfiles.

**Comment by FriederikeHanssen** [comment] 2022-11-10 19:25
ah ha, so somehow the part of the config that tells the tools to generate f1r2 files for the LEARNREADORIENTATION is not passed through
and also the normal-sample is set to "null" 😱 so your pairing doesn't actually work

**Comment by FriederikeHanssen** [comment] 2022-11-10 19:27
> It is actually the FILTERMUTECTCALLS that it is not performed. I tried the dev branch but it gives this error:
> 
> ```
> No TSV file
> No step other than "mapping" supports a directory as an input
> ```

how did you run dev?

**Comment by FriederikeHanssen** [comment] 2022-11-10 19:37
When you add this in a cusotm config:

```
process {

   withName: 'NFCORE_SAREK:SAREK:PAIR_VARIANT_CALLING:GATK_TUMOR_NORMAL_SOMATIC_VARIANT_CALLING:MUTECT2' {
   ext.args         = { params.ignore_soft_clipped_bases ?
                                "--dont-use-soft-clipped-bases true --f1r2-tar-gz ${task.ext.prefix}.f1r2.tar.gz --normal-sample ${meta.patient}_${meta.normal_id}" :
                                "--f1r2-tar-gz ${task.ext.prefix}.f1r2.tar.gz --normal-sample ${meta.patient}_${meta.normal_id}" }
   
   }
   
}
```

and then add it to the command with `-c custom.config` , does it then work?

**Comment by msguixe** [comment] 2022-11-11 11:34
> > It is actually the FILTERMUTECTCALLS that it is not performed. I tried the dev branch but it gives this error:
> > ```
> > No TSV file
> > No step other than "mapping" supports a directory as an input
> > ```
> 
> how did you run dev?

I am running it changing `-r 3.0.2` to `-r dev`

**Comment by msguixe** [comment] 2022-11-11 11:39
> When you add this in a cusotm config:
> 
> ```
> process {
> 
>    withName: 'NFCORE_SAREK:SAREK:PAIR_VARIANT_CALLING:GATK_TUMOR_NORMAL_SOMATIC_VARIANT_CALLING:MUTECT2' {
>    ext.args         = { params.ignore_soft_clipped_bases ?
>                                 "--dont-use-soft-clipped-bases true --f1r2-tar-gz ${task.ext.prefix}.f1r2.tar.gz --normal-sample ${meta.patient}_${meta.normal_id}" :
>                                 "--f1r2-tar-gz ${task.ext.prefix}.f1r2.tar.gz --normal-sample ${meta.patient}_${meta.normal_id}" }
>    
>    }
>    
> }
> ```
> 
> and then add it to the command with `-c custom.config` , does it then work?

So it is now running, with `-r 3.0.2`. I let you when it finishes.

**Comment by msguixe** [comment] 2022-11-11 13:22
It has finished with an error:
```
***********************************************************************

A USER ERROR has occurred: Bad input: Sample pt1_AQ5174 is not in BAM header: [AQ5174, pt1_AX4958]

***********************************************************************

```

**Comment by FriederikeHanssen** [comment] 2022-11-11 13:25
> > > It is actually the FILTERMUTECTCALLS that it is not performed. I tried the dev branch but it gives this error:
> > > ```
> > > No TSV file
> > > No step other than "mapping" supports a directory as an input
> > > ```
> > 
> > 
> > how did you run dev?
> 
> I am running it changing `-r 3.0.2` to `-r dev`

this looks like it picked up a sarek2 version....

**Comment by maxulysse** [comment] 2022-11-11 13:26
Can you do a `nextflow run -r dev -latest ...`

**Comment by maxulysse** [comment] 2022-11-11 13:27
or a `nextflow pull nf-core/sarek -r dev` before the `nextflow run ...` command

**Comment by FriederikeHanssen** [comment] 2022-11-11 13:30
What infrastructure are you running on?

**Comment by msguixe** [comment] 2022-11-11 13:42
> Can you do a `nextflow run -r dev -latest ...`

It looks like this worked. Trying now without the config options about sample naming...

**Comment by msguixe** [comment] 2022-11-11 13:47
> What infrastructure are you running on?

HPC cluster with CentOS Linux, and slurm

**Comment by msguixe** [comment] 2022-11-18 10:51
Hi,

Sorry it took me a while to answer, I was busy these days.
Using the` -r dev -latest` I have the same error:
`
A USER ERROR has occurred: Bad input: Sample pt1_AQ5174 is not in BAM header: [AQ5174, pt1_AX4958]
`
The pipeline finished the 11/11/22, so if you have made improvements these days these may not have been applied in this run.

I saw you released the 3.1 version. Maybe should I try with this one?

**Comment by FriederikeHanssen** [comment] 2022-11-18 11:16
🙈 yes trxy with 3.1. but also I totally missed that you are starting from `--step variant_calling`. The input files were they created with sarek?

**Comment by msguixe** [comment] 2022-11-18 11:18
> see_no_evil yes trxy with 3.1. but also I totally missed that you are starting from `--step variant_calling`. The input files were they created with sarek?

yes, bam files were already created with a previous command with sarek.

**Comment by FriederikeHanssen** [comment] 2022-11-18 11:22
ok well for some reason, the `--normal` command doesn't match. In order to finish it you could overwrite this by setting your own config:

```
process {
    withName:MUTECT2_PAIRED {
         ext.args         = { params.ignore_soft_clipped_bases ?
                                "--dont-use-soft-clipped-bases true --f1r2-tar-gz ${task.ext.prefix}.f1r2.tar.gz --normal-sample ${meta.normal_id}" :
                                "--f1r2-tar-gz ${task.ext.prefix}.f1r2.tar.gz --normal-sample ${meta.normal_id}" }
     }
}
```

The above only works for 3.1 because of some renaming that we did.

**Comment by msguixe** [comment] 2022-11-18 11:24
ok! I will try that.

**Comment by msguixe** [comment] 2022-11-22 10:25
So finally it finished. Something failed on Friday (cluster connection problem) and I had to rerun it yesterday.

For one sample, it gave me the correct output, with the filtered vcf, but not for the other.
I dont know what could have happened...
I send you de execution_trace file and the .nextflow.log
[execution_trace_2022-11-21_10-41-54.txt.gz](https://github.com/nf-core/sarek/files/10066424/execution_trace_2022-11-21_10-41-54.txt.gz)

[nextflow.log.gz](https://github.com/nf-core/sarek/files/10066426/nextflow.log.gz)

**Comment by msguixe** [comment] 2022-12-13 16:12
Hi Friederike,

Just to let you know that I have run other samples and it has worked, so I think this problem is already solved.
One important thing: it still required to assign the "normal-sample" through the conf file (--normal-sample ${meta.normal_id}), because this sarek version takes both the variables ${meta.patient_id}_${meta.normal_id} for the "normal-sample". So, if the bam is already generated through a previous release of sarek, or another tool, this specification in the conf file is necessary.
Other than that, the pipeline works fine!
Thanks for the fast and efficient feedback :)

Monica

**Comment by FriederikeHanssen** [comment] 2022-12-13 16:13
:erfect. Tahnk you for the feedback. Will close this issue then. Regarding the normal assignemnt. I am not sure how we can resolve this yet easier, since GATK unfortuantely requires this very specific annotation from the file header.

**Closed by FriederikeHanssen** 2022-12-13 16:13 UTC
Labels: bug
