### ISSUE TITLE
nextflow run nextflow-io/hello

### ISSUE THREAD

**Issue by ld9866** [nf-core/sarek#422] opened 2021-08-05 06:41 UTC
hello!
I can't use our software normally because it can't download automatically.
how can l solve this problem？
“nextflow run nextflow-io/hello“

N E X T F L O W  ~  version 21.04.3
Unknown project `nextflow-io/hello` -- NOTE: automatic download from remote repositories is disabled

**Comment by maxulysse** [comment] 2021-08-05 09:50
duplicate of #421

**Closed by maxulysse** 2021-08-05 09:50 UTC
Labels: bug
