### ISSUE TITLE
Mutect2 process skipped

### ISSUE THREAD

**Issue by PedroRaposo** [nf-core/sarek#118] opened 2020-02-19 11:36 UTC
Hello,

I'm trying to run this pipeline with as many annotators as possible. However I can only output a couple of them. One that I cannot output is Mutect2 - it seems sarek skips that process, even if I explicit my germlineResource and pon files (including both indexes). What am I missing?

Code line:
`nextflow run nf-core/sarek --input FASTQ_SUB --tools Mutect2 --germlineResource somatic-b37_af-only-gnomad.raw.sites.vcf --germlineResourceIndex somatic-b37_af-only-gnomad.raw.sites.vcf.idx --pon somatic-b37_Mutect2-WGS-panel-b37.vcf.gz --pon_index somatic-b37_Mutect2-WGS-panel-b37.vcf.idx -profile singularity -c sarek.config
`

Thank you very much,
Pedro R.

**Comment by MaxUlysse** [comment] 2020-02-19 11:57
Hi, I'm sorry you are experiencing such issues.
I will look into it, but as far as I can tell you seem to be using the right command.
May I ask which version of sarek you are using?

**Comment by PedroRaposo** [comment] 2020-02-19 12:00
Thank you @MaxUlysse for the fast response.
My version is v2.5.2.

**Comment by MaxUlysse** [comment] 2020-02-19 12:03
Can you try the dev version maybe, by adding `-r dev`:
```
nextflow run nf-core/sarek -r dev --input FASTQ_SUB --tools Mutect2 --germlineResource somatic-b37_af-only-gnomad.raw.sites.vcf --germlineResourceIndex somatic-b37_af-only-gnomad.raw.sites.vcf.idx --pon somatic-b37_Mutect2-WGS-panel-b37.vcf.gz --pon_index somatic-b37_Mutect2-WGS-panel-b37.vcf.idx -profile singularity -c sarek.config
```

**Comment by PedroRaposo** [comment] 2020-02-19 12:17
It seems I cannot pull the docker image. I'm going to try solve this problem.

FATAL:   Unable to pull docker://nfcore/sarek:dev: conveyor failed to get: Error initializing source oci:/home/(...)/.singularity/cache/oci:2d99e2e4867008446020a03ee220fed8c60e987d3d1a1278df09b04085914bb4: Error writing blob: unexpected EOF

**Comment by PedroRaposo** [comment] 2020-02-19 13:55
Hi again.
Do I have to have admin rights to run the singularity image using the dev branch?

I believe it's giving me an error related to that:
```
Command error:
  INFO:    Convert SIF file to sandbox...
  ERROR  : Failed to create user namespace
```

**Comment by MaxUlysse** [comment] 2020-02-19 14:16
OK, we did some changes on the container to enable GATK Spark.
I'll ping @nf-core/core to see if anyone ever had a similar issue.

**Comment by apeltzer** [comment] 2020-02-28 21:29
No, unfortunately, this looks rather cryptic to me, too. 

Can you run other pipelines properly on the machine affected here? e.g. nf-core/rnaseq?

**Comment by nibscles** [comment] 2020-03-05 09:57
Hi there,
I've been having the same problem, i.e. running both haplotypecaller and mutect and, while haplotypecaller yields all results, mutect is not executed without any trace of error in the logs.
I've repeated the same using the suggested "-r dev" option, and cannot confirm if it is solved or not because the development version displays another major problem with spark.
Not sure at this point if this information is appropriate in this thread, but I'm attaching the whole .command.err of the run.
You will notice that a number of Spark Tasks have failed with I/O issues which seem to originate at the MarkDuplicate step.
Happy to take have a conversation and see if we can fine tune (or disable) spark in the container and follow-up the issue.
[error.log](https://github.com/nf-core/sarek/files/4292252/error.log)

**Comment by nibscles** [comment] 2020-03-13 11:28
Hi guys,
I've been running further tests. 
This time I've been using the recalibrated bam files produced by sarek when I call with HaplotypeCaller, and then passed --step variantcalling and --tools mutect2
using the lastest nextflow release (20.01.0) and launched with the following code

```
nextflow run nf-core/sarek -r dev \
--input /usr/share/sequencing/projects/307/analysis/calls/recalibrated.tsv \
--tools mutect2 \
--targetBED /usr/share/sequencing/panels/tso/intervals/tso_intervals_merged_50-plus_hg38.bed \
--pon /usr/share/sequencing/projects/307/analysis/pon_previous/pon/pon.vcf.gz \
--pon_index /usr/share/sequencing/projects/307/analysis/pon_previous/pon/pon.vcf.gz.tbi \
--germline_resource /usr/share/sequencing/references/homo_sapiens/hg38/mutect2/af-only-gnomad.hg38.vcf.gz \
--genome GRCh38 \
--step variantcalling \
--outdir /usr/share/sequencing/projects/307/analysis/somatic_calls_dev \
-c ~/CODE/core/workflows/nextflow.config \
-profile singularity \
-with-trace \
-with-timeline nf_mutect2_timeline.htm \
-with-report nf_mutect2_report.htm
```

Looking at the logs it downloads all the files, creates all intervals and then it just shuts down reporting all processes completed ??

this is reaaaally bugging me..
[mutect2_sarek-dev_nextflow.log](https://github.com/nf-core/sarek/files/4329247/mutect2_sarek-dev_nextflow.log)

**Comment by MaxUlysse** [comment] 2020-03-13 11:57
OK, I will look deeper into that as well, and fix it for the 2.6 release.
It's now my top priority.

**Comment by ggabernet** [comment] 2020-03-17 17:30
@praveenbas you had the same issue when calling with Mutect2 + strelka, right? Do you have updates there?

**Comment by praveenbas** [comment] 2020-03-18 13:23
@ggabernet Yes, I had the same issue that Mutect2 processes were skipped in the first two attempts when used two variant detection tools (Strelka and mutect2, in my case ) but on the third attempt, it worked on the same settings. I will try to re-run the workflow (v 2.5.2) and update you accordingly.

**Comment by MaxUlysse** [comment] 2020-03-20 15:18
@nibscles I can see that you tried Mutect2 with this dev version: https://github.com/nf-core/sarek/commit/dd2a0aca551fa6300e705b27132c43497571fb9c
Can you try to update the sarek and run the actual latest code?

**Comment by MaxUlysse** [comment] 2020-03-20 15:20
Also can you run with `-ansi-log false -dump-channels` and send the log file?

**Comment by nibscles** [comment] 2020-03-20 16:07
sure, will do and report back :)

**Comment by MaxUlysse** [comment] 2020-03-26 14:09
I still didn't manage to reproduce this error.
So if anyone here as any idea, I'm OK to try

**Comment by ggabernet** [comment] 2020-03-27 10:21
@praveenbas did you manage to reproduce this error? It would be very useful for Maxime for debugging it

**Comment by nibscles** [comment] 2020-03-31 13:55
I'm trying to run the tests again. 
Unfortunately, if I run it from the "mapping" step, I get a java/spark error at the markduplicates stage.
I'm trying to run it now from the recalibrated bam files generated when I successfully run haplotypecaller, but I've restarted a couple of times because I didn't understand if it got stuck or something.. wasn't just writing anything anymore in the log.
I'll post all logs as soon as this is finished.

**Comment by MaxUlysse** [comment] 2020-03-31 14:22
Can you try with `--no_gatk_spark`? to see if there is no more spark issue on the markduplicates stage?

**Comment by nibscles** [comment] 2020-03-31 17:59
so, strangely enough using ```--no_gatk_spark``` doesn't seem to stop MarkDuplicatesSpark to be executed.
I'm attaching the logs for both:
1) start from unmapped bam files with the mapping step: failed with java/spark error on MarkDuplicates
2) start from recalibrated bam files previously produced with sarek and to run haplotypecaller, choosing Mutect2 as tool and variantcalling as step
in this case it seems to hang at some point without doing anything anymore, but I haven't seen the goodbye message so not sure what's happening. After 2 hours without any activity I have aborted.

In both cases I have used:
```
nextflow run nf-core/sarek -r dd2a0ac \
-ansi-log false \
-dump-channels \
--no_gatk_spark
```
as discussed.
[somatic_from_recalibrated.nextflow.log](https://github.com/nf-core/sarek/files/4410737/somatic_from_recalibrated.nextflow.log)
[somatic_calls_nospark.nextflow.log](https://github.com/nf-core/sarek/files/4410738/somatic_calls_nospark.nextflow.log)

**Comment by ggabernet** [comment] 2020-03-31 19:25
Hi @nibscles, maybe you need to use the latest version of dev, this is a relatively new feature. I coudn't find the `dd2a0ac` commit but it might be older.
 
```
nextflow pull nf-core/sarek -r dev
```

I tested this option today as I was also having troubles with MarkDuplicatesSpark and it worked fine for me.
The `command.sh` was:

```
#!/bin/bash -euo pipefail
gatk --java-options "-Xms4000m -Xmx7g"         MarkDuplicates         --MAX_RECORDS_IN_RAM 50000         --INPUT QBNAA012AU_ARHL085_SAMP8.bam         --METRICS_FILE QBNAA012AU_ARHL085_SAMP8.bam.metrics         --TMP_DIR .         --ASSUME_SORT_ORDER coordinate         --CREATE_INDEX true         --OUTPUT QBNAA012AU_ARHL085_SAMP8.md.bam

mv QBNAA012AU_ARHL085_SAMP8.md.bai QBNAA012AU_ARHL085_SAMP8.md.bam.bai
```

**Comment by MaxUlysse** [comment] 2020-04-01 07:55
Thanks @ggabernet I should indeed have mentioned that it was a new feature.

**Comment by nibscles** [comment] 2020-04-01 08:52
fair enough, re-running now. 
the other run though (number 2) is a bit puzzling isn't it?
I'll post the log as soon as finished

**Comment by nibscles** [comment] 2020-04-01 09:47
So I'm not entirely sure of what's happening here guys, I did run the ```-r dev``` but still executes MarkDuplicatesSpark.
The beginning of the log looks like this:
```
more .nextflow.log
Apr-01 09:50:52.227 [main] DEBUG nextflow.cli.Launcher - Setting http proxy: [wwwcache.nibsc.ac.uk, 3128]
Apr-01 09:50:52.318 [main] DEBUG nextflow.cli.Launcher - Setting https proxy: [wwwcache.nibsc.ac.uk, 3128]
Apr-01 09:50:52.318 [main] DEBUG nextflow.cli.Launcher - $> nextflow run nf-core/sarek -r dev --input /usr/share/sequencing/projects/307/analysis/umi_consensus/consensus_bams
/test_consensus_samples.tsv --tools Mutect2 --step mapping --skip_qc all --targetBED /usr/share/sequencing/panels/tso-500/intervals/tso500_manifest_intervals_merged_50-plus_h
g38.bed --pon /usr/share/sequencing/projects/307/analysis/pon_previous/pon/pon.vcf.gz --pon_index /usr/share/sequencing/projects/307/analysis/pon_previous/pon/pon.vcf.gz.tbi
--genome GRCh38 --outdir /usr/share/sequencing/projects/307/analysis/somatic_calls_nospark -c /home/AD/flescai/CODE/core/workflows/umi/umi_nextflow.config -profile singularit
y -with-trace -with-timeline nf_mutect_mapping_timeline.htm -with-report nf_mutect_mapping_report.htm -ansi-log false -dump-channels --no_gatk_spark
Apr-01 09:50:52.408 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.01.0
Apr-01 09:50:53.713 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/AD/flescai/.nextflow/assets/nf-core/sarek/.git/config; branch: master; remote: origin; url: htt
ps://github.com/nf-core/sarek.git
Apr-01 09:50:53.730 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/AD/flescai/.nextflow/assets/nf-core/sarek/.git/config; branch: master; remote: origin; url: htt
ps://github.com/nf-core/sarek.git
Apr-01 09:50:55.863 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/AD/flescai/.nextflow/assets/nf-core/sarek/.git/config; branch: master; remote: origin; url: htt
ps://github.com/nf-core/sarek.git
Apr-01 09:50:55.863 [main] INFO  nextflow.cli.CmdRun - Launching `nf-core/sarek` [jolly_mccarthy] - revision: dd2a0aca55 [dev]
Apr-01 09:50:56.660 [main] INFO  nextflow.scm.AssetManager - NOTE: Your local project version looks outdated - a different revision is available in the remote repository [983
d159377]
Apr-01 09:50:56.719 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/AD/flescai/.nextflow/assets/nf-core/sarek/nextflow.config
Apr-01 09:50:56.880 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /home/AD/flescai/CODE/core/workflows/umi/umi_nextflow.config
Apr-01 09:50:56.881 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/AD/flescai/.nextflow/assets/nf-core/sarek/nextflow.config
Apr-01 09:50:56.881 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/AD/flescai/CODE/core/workflows/umi/umi_nextflow.config
Apr-01 09:50:56.907 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Apr-01 09:50:58.199 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `singularity`
Apr-01 09:50:58.223 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [cfc_dev, denbi_qbic, genotoul, bigpurple, test_trimming, test_annotation, uppmax,
 test_tool, docker, gis, utd_ganymede, conda, singularity, munin, prince, czbiohub_aws, hebbe, cfc, uzh, ccga_med, debug, test, genouest, cbe, ebc, ccga_dx, crick, google, cz
biohub_aws_highpriority, kraken, phoenix, shh, test_splitfastq, awsbatch, pasteur, uct_hex, test_targeted, binac]
Apr-01 09:50:58.297 [main] DEBUG nextflow.Session - Session uuid: 379ebfb3-af3d-48c3-96f6-2cd8d5ff5c6b
Apr-01 09:50:58.297 [main] DEBUG nextflow.Session - Run name: jolly_mccarthy
Apr-01 09:50:58.298 [main] DEBUG nextflow.Session - Executor pool size: 32
Apr-01 09:50:58.331 [main] DEBUG nextflow.cli.CmdRun -
  Version: 20.01.0 build 5264
  Created: 12-02-2020 10:14 UTC (10:14 BST)
  System: Linux 3.10.0-957.21.3.el7.x86_64
  Runtime: Groovy 2.5.8 on OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
  Encoding: UTF-8 (UTF-8)
  Process: 5464@b1s3 [172.25.16.156]
  CPUs: 32 - Mem: 251.7 GB (163 GB) - Swap: 4 GB (2.3 GB)
```
now, I'm gonna delete entirely the assets in my ```~/.nextflow``` folder, because at this point I'm not sure it is actually downloading / updating to the latest version. Shouldn't it though?

**Comment by MaxUlysse** [comment] 2020-04-01 09:54
`NOTE: Your local project version looks outdated - a different revision is available in the remote repository`
I think you had an old version still.
But true this number 2 issue is quite troubling...
I'll try a similar command line and see if I can reproduce

**Comment by nibscles** [comment] 2020-04-01 09:58
yeah, but I was under the impression that it would update if the local version is older. apparently it doesn't. this maybe should be reported into nextflow?
I'm running again after deleting anything I had locally. will feed again test results shortly.

**Comment by MaxUlysse** [comment] 2020-04-01 10:02
I think you need to do `nextflow pull nf-core/sarek` first.
If I remember well there was a latest option, but couldn't find it in the docs

**Comment by nibscles** [comment] 2020-04-01 15:06
Nothing... with the correct version the ```--no_gatk_spark``` works, of course. But the pipeline completes recalibration and produced recalibrated bam files but then no Mutect2 run.
However, as in case no.2 above, it gets to a point where it seems to just hang in there, in the logs I can see:
```
Apr-01 11:34:08.868 [main] DEBUG nextflow.Session - Session await > all process finished
Apr-01 11:34:12.353 [main] DEBUG nextflow.Session - Session await > all barriers passed
Apr-01 15:58:33.760 [SIGINT handler] DEBUG nextflow.Session - Session aborted -- Cause: SIGINT
Apr-01 15:58:34.033 [SIGINT handler] INFO  nextflow.Session - Adieu
```
it gets to this point where it says ```Session await > all process finished``` but there is no end of workflow message, and it just seems to hang there for 4hrs until I just CTRL+C.

In the end my output folder contains the recalibrated files, but no variant calling with mutect2 results.
[nospark_from_umapped_bam.nextflow.log](https://github.com/nf-core/sarek/files/4416015/nospark_from_umapped_bam.nextflow.log)

**Comment by ggabernet** [comment] 2020-04-01 17:46
Can you try to provide `--tools mutect2` instead of `Mutect2`?

**Comment by MaxUlysse** [comment] 2020-04-02 06:10
Yes, code check for mutect2 but the input for tools is lowercased.
So it won't change a thing

**Comment by ggabernet** [comment] 2020-04-02 06:32
Ah ok I missed that 🙂

**Comment by MaxUlysse** [comment] 2020-04-02 07:02
It's this part in the code:
```
tools = params.tools ? params.tools.split(',').collect{it.trim().toLowerCase()} : []
```
I figure no one will actually remember if it's `Mutect2`, `MuTect2`, `MUTECT2` or just simply `mutect2`, so I lowercased everything ;-)

**Comment by ggabernet** [comment] 2020-04-02 07:40
Makes a lot of sense!

**Comment by ggabernet** [comment] 2020-04-02 08:18
Hi, @silviamorins had a very similar thing today with the `freebayes` VC. The workflow completed without errors but the results for the variant calling are not there.

[freebayes_nextflow.log](https://github.com/nf-core/sarek/files/4419673/freebayes_nextflow.log)

**Comment by MaxUlysse** [comment] 2020-04-02 08:20
I'll have a look right now

**Comment by ggabernet** [comment] 2020-04-02 08:22
We can resume with `-ansi-log false -dump-channels` and send the log again

**Comment by MaxUlysse** [comment] 2020-04-02 08:49
I ran `nextflow run nf-core/sarek -r 2.6 -profile test,docker --tools Freebayes`
and I got results:
```
≻ls -1 results/VariantCalling/9876T_vs_1234N/FreeBayes/
FreeBayes_9876T_vs_1234N.vcf.gz
FreeBayes_9876T_vs_1234N.vcf.gz.tbi
```

**Comment by nibscles** [comment] 2020-04-02 10:10
ok, I think I understand now.
2 things.

1) I've run the test using ```nextflow run nf-core/sarek -r dev -c /home/AD/flescai/CODE/core/workflows/umi/umi_nextflow.config -profile test,singularity --tools mutect2```

and got this error on one of the steps

```
Apr-02 10:47:23.015 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'CalculateContamination (9876T_vs_1234N)'

Caused by:
  Process `CalculateContamination (9876T_vs_1234N)` terminated with an error exit status (3)

Command executed:

  # calculate contamination
  gatk --java-options "-Xmx6g"         CalculateContamination         -I 9876T_pileupsummaries.table         -O 9876T_contamination.table

Command exit status:
  3

Command output:
  (empty)

Command error:
  Using GATK jar /opt/conda/envs/nf-core-sarek-dev/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar
  Running:
      java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx6g -jar /opt/conda/envs/nf-core-sarek-dev/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar CalculateContamination -I 9876T_pileupsummaries.table -O 9876T_contamination.table
  09:47:18.112 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/conda/envs/nf-core-sarek-dev/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
  Apr 02, 2020 9:47:18 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
  INFO: Failed to detect whether we are running on Google Compute Engine.
  09:47:18.491 INFO  CalculateContamination - ------------------------------------------------------------
  09:47:18.491 INFO  CalculateContamination - The Genome Analysis Toolkit (GATK) v4.1.6.0
  09:47:18.492 INFO  CalculateContamination - For support and documentation go to https://software.broadinstitute.org/gatk/
  09:47:18.492 INFO  CalculateContamination - Executing as flescai@b1s3 on Linux v3.10.0-957.21.3.el7.x86_64 amd64
  09:47:18.492 INFO  CalculateContamination - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_192-b01
  09:47:18.492 INFO  CalculateContamination - Start Date/Time: April 2, 2020 9:47:18 AM UTC
  09:47:18.492 INFO  CalculateContamination - ------------------------------------------------------------
  09:47:18.492 INFO  CalculateContamination - ------------------------------------------------------------
  09:47:18.493 INFO  CalculateContamination - HTSJDK Version: 2.21.2
  09:47:18.493 INFO  CalculateContamination - Picard Version: 2.21.9
  09:47:18.493 INFO  CalculateContamination - HTSJDK Defaults.COMPRESSION_LEVEL : 2
  09:47:18.493 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
  09:47:18.493 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
  09:47:18.494 INFO  CalculateContamination - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
  09:47:18.494 INFO  CalculateContamination - Deflater: IntelDeflater
  09:47:18.494 INFO  CalculateContamination - Inflater: IntelInflater
  09:47:18.494 INFO  CalculateContamination - GCS max retries/reopens: 20
  09:47:18.494 INFO  CalculateContamination - Requester pays: disabled
  09:47:18.494 INFO  CalculateContamination - Initializing engine
  09:47:18.494 INFO  CalculateContamination - Done initializing engine
  09:47:18.614 INFO  CalculateContamination - Shutting down engine
  [April 2, 2020 9:47:18 AM UTC] org.broadinstitute.hellbender.tools.walkers.contamination.CalculateContamination done. Elapsed time: 0.01 minutes.
  Runtime.totalMemory()=2124939264
  java.lang.IllegalStateException: some data line value remains undefined: e.g. column 'sample' index 0
        at org.broadinstitute.hellbender.utils.tsv.DataLine.unpack(DataLine.java:150)
        at org.broadinstitute.hellbender.utils.tsv.TableWriter.writeRecord(TableWriter.java:203)
        at org.broadinstitute.hellbender.utils.tsv.TableWriter.writeAllRecords(TableWriter.java:224)
        at org.broadinstitute.hellbender.tools.walkers.contamination.ContaminationRecord.writeToFile(ContaminationRecord.java:43)
        at org.broadinstitute.hellbender.tools.walkers.contamination.CalculateContamination.doWork(CalculateContamination.java:132)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)
```

this is something you might want to look at but not relevant for this issue.
Running the test data, I did get mutect variant calling and noticed that the VCF file was only present into the Tumour_vs_Normal folder.
Then I inspected the code in sarek dev:

```
gatk --java-options "-Xmx${task.memory.toGiga()}g" \
      Mutect2 \
      -R ${fasta}\
      -I ${bamTumor}  -tumor ${idSampleTumor} \
      -I ${bamNormal} -normal ${idSampleNormal} \
      ${intervalsOptions} \
      --germline-resource ${germlineResource} \
      ${PON} \
      -O ${intervalBed.baseName}_${idSampleTumor}_vs_${idSampleNormal}.vcf
```

this means Sarek is bound to produce a result **only** if there's a tumour normal pair.
this **not** how it is currently generalised:
https://gatk.broadinstitute.org/hc/en-us/articles/360035531132--How-to-Call-somatic-mutations-using-GATK4-Mutect2
the tumor-normal pair is a quite specific case of somatic calling, which has now been generalised on a per-sample base, to widen the applications: which why the Panel of Normals as well as the use of Germline Resource are recommended for.

Conclusion: Mutect2 from Sarek on my samples doesn't run because **I don't have tumour-normal pairs**, and therefore the code scripted in the process would not produce any result.
Strangely enough however I don't get any error, but if the normal sample is a channel, the channel will be empty and the process will not be executed.

So perhaps we should:
1) clarify more explicitly in the documentation (if it's there, I've missed I'm sorry)
2) decide what to do, because this quite important part of the pipeline (somatic mutation) is currently limited to a very specific case scenario.

**Comment by ggabernet** [comment] 2020-04-02 10:25
Ah same here, the samples that @silviamorins was analyzing do not have tumor-normal pairs, but are only meant for germline variant calling. Sorry I did not have a close look to the experimental design.

**Comment by MaxUlysse** [comment] 2020-04-02 10:45
Oooh, I see.
At the beginning Sarek was designed as a tumor/normal analysis pipeline.
So we don't really handle tumor only at the moment.

But I can see that it could definitively be useful.

**Comment by MaxUlysse** [comment] 2020-04-02 10:47
I guess here is the documentation that should explain it should be run on T/N pairs only:
https://github.com/nf-core/sarek/blob/dev/docs/output.md#gatk-mutect2

**Comment by nibscles** [comment] 2020-04-02 10:51
Yeah I guess I've interpreted "For a Tumor/Normal pair only: Output directory" as that director is created when you have a tumour/normal pair.
I think it should be explicited with something like "At the moment only Tumour/Normal pair mode can be run", which is not the current default in GATK.
I'd be happy to help with the code for a more general execution if that fits the plans. We definitely have to have the code in place now for our analyses.

**Comment by MaxUlysse** [comment] 2020-04-02 10:52
Then let's go for it.
I propose to delay the 2.6 release to include that then.

@szilvajuhos you might be interested by this discussion.

**Comment by MaxUlysse** [comment] 2020-05-24 10:18
So Tumour only mode for Mutect2 will be included in 3.0, so closing this issue

**Closed by MaxUlysse** 2020-05-24 10:18 UTC
Labels: bug, help wanted

**Comment by benbfly** [comment] 2020-08-03 17:11
just checking in if anyone's worked on this yet, we also need a tumor-only pipeline.  It's pretty commonly used in the mutect2 community (famously, some of the clinical tumor sequencing services do not use matched normals).  Thanks!

**Comment by MaxUlysse** [comment] 2020-08-03 20:16
Hi @benbfly, we're currently working on porting sarek to DSL2, so no efforts on that direction at the moment, but we'll be working onto a tumor-only pipeline hopefully afterwards.
