### ISSUE TITLE
[FEATURE] Extensions understanding

### ISSUE THREAD

**Issue by TaynaP** [nf-core/sarek#351] opened 2021-02-22 14:00 UTC
## Is your feature request related to a problem? Please describe

Hi !

After running the profile "test", certain html files have a .1 or .2 extensions in the pipeline_info folder (like "execution_report.html.1"), and they are not recognized by every software.

## Describe the solution you'd like

I would like to have only html files without extensions like .1.

## Describe alternatives you've considered

Maybe we could consider renaming them instead of having .1 and .2 extensions ?

## Additional context

I recently discovered Sarek and I used Sarek v2.7.

From what I've noticed the difference between those files comes from the docker container's name but I'm not sure.
Is this due to Docker ? I didn't really find any info in the documentation.

Could you enlighten me on this subject ?

Thanks

**Comment by FriederikeHanssen** [comment] 2021-02-22 14:25
Hi @TaynaP! The extension labels come from nextflow itself and are generating by resuming the pipeline:

First resume: `execution.html.1`, second `execution.html.2` and so on. Here for example I resumed a bunch of times:

```
-rw-r--r-- 1 6.4M Feb 22 03:35 execution_report.html
-rw-r--r-- 1 4.9M Feb 18 11:08 execution_report.html.1
-rw-r--r-- 1 4.2M Feb 17 11:15 execution_report.html.2
-rw-r--r-- 1 4.2M Feb 17 11:14 execution_report.html.3
-rw-r--r-- 1 4.2M Feb 17 10:28 execution_report.html.4
```

Everything, however, is collected in one `execution.html`, which should be the latest file. The previously completed process are labelled as `cached`, but you can still find all the information like runtime etc. pp. in there. See attached screenshot. 
![Screenshot 2021-02-22 at 15 20 18](https://user-images.githubusercontent.com/12273093/108720776-8a530800-7521-11eb-8d84-cde56cc54c2f.png)

**Comment by TaynaP** [comment] 2021-03-04 07:44
Hi!
I didn't really understand what you meant. Are they there in case the pipeline stops in the middle? But then why do we them when we launch the "test" profile? And could you tell me where the image is coming from? I'm not very familiar with Nextflow. 
Thanks!

**Comment by FriederikeHanssen** [comment] 2021-03-04 09:09
Do you know the `-resume` command? It can be used for restarting the pipeline from the last process it ran through. This is useful and a real time saver when the pipeline fails for whichever reason, since you do not have to repeat already computed steps. Check the nextflow documentation for more on this command: https://www.nextflow.io/docs/latest/getstarted.html?highlight=resume#modify-and-resume 
also there a some blog entries describing more resume functionality: 
https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html 
https://www.nextflow.io/blog/2019/troubleshooting-nextflow-resume.html
https://nf-co.re/usage/introduction#tips-and-tricks

Can you describe and post the commands on how exactly you ran sarek 2.7 with the test profile? Did you create an empty directory and then ran it with in there? 

I tried reproducing what you get, by starting with a completely fresh workspace:

```
nextflow pull nf-core/sarek  -r 2.7
nextflow run nf-core/sarek -r 2.7 -profile <institute>,test
```

here is the output from `results/pipeline_info`:
```
Mar  4 09:43 execution_report.html
Mar  4 09:43 execution_timeline.html
Mar  4 09:43 execution_trace.txt
Mar  4 09:43 pipeline_dag.dot
Mar  4 09:43 pipeline_report.html
Mar  4 09:43 pipeline_report.txt
Mar  4 09:43 software_versions.csv
```

if I now don't change anything, but restart the command with `-resume`:
```
nextflow run nf-core/sarek -r 2.7 -profile <institute>,test -resume
```

then some of the processes will be labeled as `cached` (since they ran through successful in the first run,  some processes won't be resumed as per nf-core rule). `results/pipeline_info` then shows:
```
Mar  4 09:51 execution_report.html
Mar  4 09:43 execution_report.html.1
Mar  4 09:51 execution_timeline.html
Mar  4 09:43 execution_timeline.html.1
Mar  4 09:51 execution_trace.txt
Mar  4 09:43 execution_trace.txt.1
Mar  4 09:51 pipeline_dag.dot
Mar  4 09:51 pipeline_report.html
Mar  4 09:51 pipeline_report.txt
Mar  4 09:49 software_versions.csv
```

As you can see there are now 2 `execution_reports` with 2 different time stamps. The one ending in `.1` is from the first run I did and was renamed by nextflow, but saved in case I want to take a look. The one ending in just `.html` is from the second run (the one with `-resume`). It contains all the information from the first run + all new information from the second run, so normally it is good enough to just take a look there. And as you pointed out you easily load it in the browser ( to load the one with `.html.1` just rename it to end with `.html`). The processes labeled as `cached` are the ones that have been completed in a previous run. 

The image I took in the post above is from one of `execution_reports` to show you `cached` processes. 

I will append the two execution reports from the two test runs I did for this post, so you can take a look at them.
[execution.zip](https://github.com/nf-core/sarek/files/6082199/execution.zip)

**Comment by FriederikeHanssen** [comment] 2021-03-04 09:52
Since this issue is not sarek related, I will close it. Join us on [slack](https://nf-co.re/join/slack), if you like and if you have more nextflow related questions, definitely check out [nextflow gitter](https://gitter.im/nextflow-io/nextflow).

**Closed by FriederikeHanssen** 2021-03-04 09:52 UTC
Labels: enhancement
