### ISSUE TITLE
[BUG] No variantcalling output is generated

### ISSUE THREAD

**Issue by bounlu** [nf-core/sarek#543] opened 2022-05-11 09:41 UTC
## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/sarek pipeline documentation](https://nf-co.re/sarek/usage)
- [ ] https://github.com/nf-core/sarek/issues/118

## Description of the bug

Although I specify the tools for variant calling as below, no relevant output is generated, and no error/log is displayed as well.

## Steps to reproduce

I run it on AWS Batch with the following command and configs and input:

```
nextflow run nf-core/sarek \
-profile docker \
--genome 'hg38' \
--input 'samplesheet.csv' \
--step mapping \
--aligner bwa-mem2 \
--tools mpileup,mutect2,snpeff,strelka,vep \
--outdir 's3://omeran/nextflow/sarek/results/' \
-work-dir 's3://omeran/nextflow/sarek/work/' \
-c '/Users/omeran/Desktop/aws/sarek/custom.config' \
-r dev \
-resume
```

`custom.config` file:
```
process.executor	= 'awsbatch'
process.queue		= 'omeran-nextflow-sarek-spot'
aws.batch.cliPath	= '/home/ec2-user/miniconda/bin/aws'
```
`samplesheet.csv` file:
```
subject,sex,status,sample,lane,fastq1,fastq2
DNBSEQ,XX,1,DNBSEQ_tumour,1,s3://fastq/xxx/V350040544_L01_111-606_1.fq.gz,s3://fastq/xxx/V350040544_L01_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,2,s3://fastq/xxx/V350040544_L01_111-607_1.fq.gz,s3://fastq/xxx/V350040544_L01_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,3,s3://fastq/xxx/V350040544_L01_111-608_1.fq.gz,s3://fastq/xxx/V350040544_L01_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,4,s3://fastq/xxx/V350040544_L01_111-609_1.fq.gz,s3://fastq/xxx/V350040544_L01_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,5,s3://fastq/xxx/V350040544_L01_111-610_1.fq.gz,s3://fastq/xxx/V350040544_L01_111-610_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,6,s3://fastq/xxx/V350040544_L02_111-606_1.fq.gz,s3://fastq/xxx/V350040544_L02_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,7,s3://fastq/xxx/V350040544_L02_111-607_1.fq.gz,s3://fastq/xxx/V350040544_L02_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,8,s3://fastq/xxx/V350040544_L02_111-608_1.fq.gz,s3://fastq/xxx/V350040544_L02_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,9,s3://fastq/xxx/V350040544_L02_111-609_1.fq.gz,s3://fastq/xxx/V350040544_L02_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,10,s3://fastq/xxx/V350040544_L02_111-610_1.fq.gz,s3://fastq/xxx/V350040544_L02_111-610_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,11,s3://fastq/xxx/V350040544_L03_111-606_1.fq.gz,s3://fastq/xxx/V350040544_L03_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,12,s3://fastq/xxx/V350040544_L03_111-607_1.fq.gz,s3://fastq/xxx/V350040544_L03_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,13,s3://fastq/xxx/V350040544_L03_111-608_1.fq.gz,s3://fastq/xxx/V350040544_L03_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,14,s3://fastq/xxx/V350040544_L03_111-609_1.fq.gz,s3://fastq/xxx/V350040544_L03_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,15,s3://fastq/xxx/V350040544_L03_111-610_1.fq.gz,s3://fastq/xxx/V350040544_L03_111-610_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,16,s3://fastq/xxx/V350040601_L01_111-606_1.fq.gz,s3://fastq/xxx/V350040601_L01_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,17,s3://fastq/xxx/V350040601_L01_111-607_1.fq.gz,s3://fastq/xxx/V350040601_L01_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,18,s3://fastq/xxx/V350040601_L01_111-608_1.fq.gz,s3://fastq/xxx/V350040601_L01_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,19,s3://fastq/xxx/V350040601_L01_111-609_1.fq.gz,s3://fastq/xxx/V350040601_L01_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,20,s3://fastq/xxx/V350040601_L01_111-610_1.fq.gz,s3://fastq/xxx/V350040601_L01_111-610_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,21,s3://fastq/xxx/V350040601_L02_111-606_1.fq.gz,s3://fastq/xxx/V350040601_L02_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,22,s3://fastq/xxx/V350040601_L02_111-607_1.fq.gz,s3://fastq/xxx/V350040601_L02_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,23,s3://fastq/xxx/V350040601_L02_111-608_1.fq.gz,s3://fastq/xxx/V350040601_L02_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,24,s3://fastq/xxx/V350040601_L02_111-609_1.fq.gz,s3://fastq/xxx/V350040601_L02_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,25,s3://fastq/xxx/V350040601_L02_111-610_1.fq.gz,s3://fastq/xxx/V350040601_L02_111-610_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,26,s3://fastq/xxx/V350040601_L03_111-606_1.fq.gz,s3://fastq/xxx/V350040601_L03_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,27,s3://fastq/xxx/V350040601_L03_111-607_1.fq.gz,s3://fastq/xxx/V350040601_L03_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,28,s3://fastq/xxx/V350040601_L03_111-608_1.fq.gz,s3://fastq/xxx/V350040601_L03_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,29,s3://fastq/xxx/V350040601_L03_111-609_1.fq.gz,s3://fastq/xxx/V350040601_L03_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,30,s3://fastq/xxx/V350040601_L03_111-610_1.fq.gz,s3://fastq/xxx/V350040601_L03_111-610_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,31,s3://fastq/xxx/V350040622_L01_111-606_1.fq.gz,s3://fastq/xxx/V350040622_L01_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,32,s3://fastq/xxx/V350040622_L01_111-607_1.fq.gz,s3://fastq/xxx/V350040622_L01_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,33,s3://fastq/xxx/V350040622_L01_111-608_1.fq.gz,s3://fastq/xxx/V350040622_L01_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,34,s3://fastq/xxx/V350040622_L01_111-609_1.fq.gz,s3://fastq/xxx/V350040622_L01_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,35,s3://fastq/xxx/V350040622_L01_111-610_1.fq.gz,s3://fastq/xxx/V350040622_L01_111-610_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,36,s3://fastq/xxx/V350040622_L02_111-606_1.fq.gz,s3://fastq/xxx/V350040622_L02_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,37,s3://fastq/xxx/V350040622_L02_111-607_1.fq.gz,s3://fastq/xxx/V350040622_L02_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,38,s3://fastq/xxx/V350040622_L02_111-608_1.fq.gz,s3://fastq/xxx/V350040622_L02_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,39,s3://fastq/xxx/V350040622_L02_111-609_1.fq.gz,s3://fastq/xxx/V350040622_L02_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,40,s3://fastq/xxx/V350040622_L02_111-610_1.fq.gz,s3://fastq/xxx/V350040622_L02_111-610_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,41,s3://fastq/xxx/V350040622_L03_111-606_1.fq.gz,s3://fastq/xxx/V350040622_L03_111-606_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,42,s3://fastq/xxx/V350040622_L03_111-607_1.fq.gz,s3://fastq/xxx/V350040622_L03_111-607_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,43,s3://fastq/xxx/V350040622_L03_111-608_1.fq.gz,s3://fastq/xxx/V350040622_L03_111-608_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,44,s3://fastq/xxx/V350040622_L03_111-609_1.fq.gz,s3://fastq/xxx/V350040622_L03_111-609_2.fq.gz
DNBSEQ,XX,1,DNBSEQ_tumour,45,s3://fastq/xxx/V350040622_L03_111-610_1.fq.gz,s3://fastq/xxx/V350040622_L03_111-610_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,1,s3://fastq/yyy/V350040544_L01_222-611_1.fq.gz,s3://fastq/yyy/V350040544_L01_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,2,s3://fastq/yyy/V350040544_L01_222-612_1.fq.gz,s3://fastq/yyy/V350040544_L01_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,3,s3://fastq/yyy/V350040544_L01_222-613_1.fq.gz,s3://fastq/yyy/V350040544_L01_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,4,s3://fastq/yyy/V350040544_L01_222-614_1.fq.gz,s3://fastq/yyy/V350040544_L01_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,5,s3://fastq/yyy/V350040544_L01_222-615_1.fq.gz,s3://fastq/yyy/V350040544_L01_222-615_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,6,s3://fastq/yyy/V350040544_L02_222-611_1.fq.gz,s3://fastq/yyy/V350040544_L02_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,7,s3://fastq/yyy/V350040544_L02_222-612_1.fq.gz,s3://fastq/yyy/V350040544_L02_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,8,s3://fastq/yyy/V350040544_L02_222-613_1.fq.gz,s3://fastq/yyy/V350040544_L02_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,9,s3://fastq/yyy/V350040544_L02_222-614_1.fq.gz,s3://fastq/yyy/V350040544_L02_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,10,s3://fastq/yyy/V350040544_L02_222-615_1.fq.gz,s3://fastq/yyy/V350040544_L02_222-615_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,11,s3://fastq/yyy/V350040544_L03_222-611_1.fq.gz,s3://fastq/yyy/V350040544_L03_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,12,s3://fastq/yyy/V350040544_L03_222-612_1.fq.gz,s3://fastq/yyy/V350040544_L03_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,13,s3://fastq/yyy/V350040544_L03_222-613_1.fq.gz,s3://fastq/yyy/V350040544_L03_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,14,s3://fastq/yyy/V350040544_L03_222-614_1.fq.gz,s3://fastq/yyy/V350040544_L03_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,15,s3://fastq/yyy/V350040544_L03_222-615_1.fq.gz,s3://fastq/yyy/V350040544_L03_222-615_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,16,s3://fastq/yyy/V350040601_L01_222-611_1.fq.gz,s3://fastq/yyy/V350040601_L01_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,17,s3://fastq/yyy/V350040601_L01_222-612_1.fq.gz,s3://fastq/yyy/V350040601_L01_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,18,s3://fastq/yyy/V350040601_L01_222-613_1.fq.gz,s3://fastq/yyy/V350040601_L01_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,19,s3://fastq/yyy/V350040601_L01_222-614_1.fq.gz,s3://fastq/yyy/V350040601_L01_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,20,s3://fastq/yyy/V350040601_L01_222-615_1.fq.gz,s3://fastq/yyy/V350040601_L01_222-615_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,21,s3://fastq/yyy/V350040601_L02_222-611_1.fq.gz,s3://fastq/yyy/V350040601_L02_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,22,s3://fastq/yyy/V350040601_L02_222-612_1.fq.gz,s3://fastq/yyy/V350040601_L02_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,23,s3://fastq/yyy/V350040601_L02_222-613_1.fq.gz,s3://fastq/yyy/V350040601_L02_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,24,s3://fastq/yyy/V350040601_L02_222-614_1.fq.gz,s3://fastq/yyy/V350040601_L02_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,25,s3://fastq/yyy/V350040601_L02_222-615_1.fq.gz,s3://fastq/yyy/V350040601_L02_222-615_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,26,s3://fastq/yyy/V350040601_L03_222-611_1.fq.gz,s3://fastq/yyy/V350040601_L03_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,27,s3://fastq/yyy/V350040601_L03_222-612_1.fq.gz,s3://fastq/yyy/V350040601_L03_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,28,s3://fastq/yyy/V350040601_L03_222-613_1.fq.gz,s3://fastq/yyy/V350040601_L03_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,29,s3://fastq/yyy/V350040601_L03_222-614_1.fq.gz,s3://fastq/yyy/V350040601_L03_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,30,s3://fastq/yyy/V350040601_L03_222-615_1.fq.gz,s3://fastq/yyy/V350040601_L03_222-615_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,31,s3://fastq/yyy/V350040622_L01_222-611_1.fq.gz,s3://fastq/yyy/V350040622_L01_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,32,s3://fastq/yyy/V350040622_L01_222-612_1.fq.gz,s3://fastq/yyy/V350040622_L01_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,33,s3://fastq/yyy/V350040622_L01_222-613_1.fq.gz,s3://fastq/yyy/V350040622_L01_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,34,s3://fastq/yyy/V350040622_L01_222-614_1.fq.gz,s3://fastq/yyy/V350040622_L01_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,35,s3://fastq/yyy/V350040622_L01_222-615_1.fq.gz,s3://fastq/yyy/V350040622_L01_222-615_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,36,s3://fastq/yyy/V350040622_L02_222-611_1.fq.gz,s3://fastq/yyy/V350040622_L02_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,37,s3://fastq/yyy/V350040622_L02_222-612_1.fq.gz,s3://fastq/yyy/V350040622_L02_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,38,s3://fastq/yyy/V350040622_L02_222-613_1.fq.gz,s3://fastq/yyy/V350040622_L02_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,39,s3://fastq/yyy/V350040622_L02_222-614_1.fq.gz,s3://fastq/yyy/V350040622_L02_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,40,s3://fastq/yyy/V350040622_L02_222-615_1.fq.gz,s3://fastq/yyy/V350040622_L02_222-615_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,41,s3://fastq/yyy/V350040622_L03_222-611_1.fq.gz,s3://fastq/yyy/V350040622_L03_222-611_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,42,s3://fastq/yyy/V350040622_L03_222-612_1.fq.gz,s3://fastq/yyy/V350040622_L03_222-612_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,43,s3://fastq/yyy/V350040622_L03_222-613_1.fq.gz,s3://fastq/yyy/V350040622_L03_222-613_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,44,s3://fastq/yyy/V350040622_L03_222-614_1.fq.gz,s3://fastq/yyy/V350040622_L03_222-614_2.fq.gz
DNBSEQ,XX,0,DNBSEQ_normal,45,s3://fastq/yyy/V350040622_L03_222-615_1.fq.gz,s3://fastq/yyy/V350040622_L03_222-615_2.fq.gz
Novaseq,XX,1,Novaseq_tumour,1,s3://fastq/zzz/FCH3NJ5DSX3_L4_333-101_1.fq.gz,s3://fastq/zzz/FCH3NJ5DSX3_L4_333-101_2.fq.gz
Novaseq,XX,0,Novaseq_normal,1,s3://fastq/ttt/FCH3NJ5DSX3_L4_444-96_1.fq.gz,s3://fastq/ttt/FCH3NJ5DSX3_L4_444-96_2.fq.gz
```

**Output:**
```
-[nf-core/sarek] Pipeline completed successfully-
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Completed at: 11-May-2022 17:26:01
Duration    : 8m 25s
CPU hours   : 0.1 (91% cached)
Succeeded   : 2
Cached      : 41
```

```
$ aws s3 ls s3://omeran/nextflow/sarek/results/
                           PRE build/
                           PRE multiqc/
                           PRE pipeline_info/
                           PRE preprocessing/
```

**Expected behaviour:**
`results/VariantCalling` folder should be created.

What am I doing wrong?

**Info:**

N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/nf-core/sarek` [golden_torvalds] DSL2 - revision: 3bcf3bbcb6 [dev]

**Comment by FriederikeHanssen** [comment] 2022-05-11 09:46
Hi! Thank you testing `dev`!!  Just so you know, Mutect2 still needs fixing and probably won't generate useful results, and mpileup only runs in combination with ControlFreec.
 
 what is in the `build` folder?
Can you send me the nextflow.log?

**Comment by bounlu** [comment] 2022-05-11 09:53
I see, then I will test it alone with `mutect2` on the `master` branch.

This is the content of the build folder:

$ aws s3 ls s3://omeran/nextflow/sarek/results/build/
2022-05-11 17:44:28          0 
2022-05-11 17:10:26       4890 genome.fa.bed

Unfortunately I can't send you the log folder.

**Comment by bounlu** [comment] 2022-05-11 10:00
When I tried to run it with `mutect2` alone on the `master` branch, I got another error:

```
May-11 17:57:20.055 [main] DEBUG nextflow.Session - Session aborted -- Cause: Channel `create` method is not supported any more
May-11 17:57:20.071 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.DeprecationException: Channel `create` method is not supported any more
	at nextflow.Channel.create(Channel.groovy:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1529)
	at groovy.lang.DelegatingMetaClass.invokeStaticMethod(DelegatingMetaClass.java:154)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:50)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at Script_c3d27a41.extractFastqFromDir(Script_c3d27a41:4132)
	at Script_c3d27a41$extractFastqFromDir$2.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at Script_c3d27a41.runScript(Script_c3d27a41:158)
	at nextflow.script.BaseScript.runDsl2(BaseScript.groovy:170)
	at nextflow.script.BaseScript.run(BaseScript.groovy:203)
	at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:220)
	at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:212)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:120)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:334)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)

```

**Comment by FriederikeHanssen** [comment] 2022-05-11 11:05
Which nextflow version are you using? I am suspecting that it is the new 22.04 which doesn't supprt DSL1 by default anymore. You could try with prepending `export NXF_DEFAULT_DSL=1`or use the previous nextflow version

**Comment by bounlu** [comment] 2022-05-11 11:31
I also tried that (DSL1), but I got another error:

N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/nf-core/sarek` [distracted_ardinghelli] DSL1 - revision: 68b9930a74 [master]


------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
      ____
    .´ _  `.
   /  |\`-_ \      __        __   ___     
  |   | \  `-|    |__`  /\  |__) |__  |__/
   \ |   \  /     .__| /¯¯\ |  \ |___ |  \
    `|____\´

  nf-core/sarek v2.7.1
------------------------------------------------------

No TSV file
Reading /Users/omeran/Desktop/aws/sarek/samplesheet.csv directory
WARN: [nf-core/sarek] in /Users/omeran/Desktop/aws/sarek/samplesheet.csv directory, all fastqs are assuming to be from the same sample, which is assumed to be a germline one
No FASTQ files found in --input directory '/Users/omeran/Desktop/aws/sarek/samplesheet.csv'

**Comment by FriederikeHanssen** [comment] 2022-05-11 11:41
ah no, but sarek 2.7.1 (so the latest release) requires a TSV file as input (no header). Sorry for all the trouble :(

**Comment by bounlu** [comment] 2022-05-11 11:50
Ahh I see, switching to TSV format (also changing the file extension to .tsv) and removing the header fixed the problem!

I hope you will update the pipeline to DSL2 soon though to avoid this confusion!

**Comment by FriederikeHanssen** [comment] 2022-05-16 17:10
FYI: Just merged a PR fixing mutect2 on the dev branch, in case you want to try it again

**Comment by bounlu** [comment] 2022-05-17 01:54
Thanks for the update! May I ask if the `dev` branch has `--sentieon` option available for the alignment?

**Comment by FriederikeHanssen** [comment] 2022-05-17 06:39
No, not yet. It has BWA, BWAMem2 (index must be computed), DragMap (index must be computed)

**Comment by FriederikeHanssen** [comment] 2022-05-17 06:40
I looked into your other error. I couldn't reproduce the error you have with the results not being present.

**Comment by FriederikeHanssen** [comment] 2022-05-17 06:47
ah I have an idea. Did Baserecalibration run? The step requires known_indels which are not specified as far as I see. So if that is the case then Variantcalling can't be run. If you want to skip baserecalibration, set `--skip_tools baserecalibrator` . Let me know if it works. Then I will add a warning message to the log to make this more apparent

**Comment by FriederikeHanssen** [comment] 2022-05-23 12:51
@bounlu dragmap and & bwamem2 indices are now available for GATK.GRCh38. . Could you confim my suspicision about missing indels file?

**Comment by Laolga** [comment] 2022-05-24 12:24
Hi! I have a similar problem. Also, no variant calling output. But I'm using tsv file without a header. Nextflow version is 20.10.0. No errors in the log, but only these files are produced:
```
0K	./VariantCalling/TSV
80K	./VariantCalling
1.5M	./Reports/MultiQC/multiqc_report.html
40K	./Reports/MultiQC/multiqc_plots
64K	./Reports/MultiQC/multiqc_data/multiqc_data.json
64K	./Reports/MultiQC/multiqc_data/multiqc_sources.txt
128K	./Reports/MultiQC/multiqc_data/multiqc.log
64K	./Reports/MultiQC/multiqc_data/multiqc_qualimap_bamqc_genome_results.txt
360K	./Reports/MultiQC/multiqc_data
1.9M	./Reports/MultiQC
1.9M	./Reports
64K	./pipeline_info/execution_trace_2022-05-24_13-21-11.txt
64K	./pipeline_info/pipeline_report.txt
96K	./pipeline_info/pipeline_report.html
728K	./pipeline_info/pipeline_dag_2022-05-24_13-21-11.svg
3.6M	./pipeline_info/execution_report_2022-05-24_13-21-11.html
224K	./pipeline_info/results_description.html
64K	./pipeline_info/software_versions.csv
4.9M	./pipeline_info
40K	./Preprocessing/TSV
80K	./Preprocessing
```

The command I used is 
`nextflow run nf-core/sarek -profile singularity --input wgs_config.tsv --step variant_calling --genome hg19`

` wgs_config.tsv`  looks like this:

```
a	XY	1	ap1	/ap1_merged.bam.rmdup.bam	/ap1_merged.bam.rmdup.bam.bai
b	XY	1	bp2	/bp2_merged.bam.rmdup.bam	/bp2_merged.bam.rmdup.bam.bai

```

**Comment by FriederikeHanssen** [comment] 2022-05-24 12:42
so the tsv file indicates to me, that you are using DSL1 version of sarek, which on exactly. In order to generate an output for variant calling you need to add the parameter `--tools` and then specify which tool(s) you would like to use for variantcalling. Since in the above command none are added no variantcalling will be done. More infor on which tools are available:  https://nf-co.re/sarek/2.7.1/parameters#tools

**Closed by FriederikeHanssen** 2022-05-24 12:42 UTC
Labels: bug

**Comment by Laolga** [comment] 2022-05-24 14:48
I'm using `nf-core/sarek` [scruffy_noyce] - revision: 68b9930a74
Running  `nextflow run nf-core/sarek -profile singularity --input wgs_config.tsv --step variant_calling --genome hg19 -resume --tools mpileup,mutect2,control-freec,vep` also does not produce output and the log file does not provide any details just:

```
-[nf-core/sarek] Pipeline completed with errors-
```

**Comment by FriederikeHanssen** [comment] 2022-05-24 14:54
can you please provide the `.nextflow.log` and the complete terminal output?
