### ISSUE TITLE
vcf-file from mpileup is not getting annotated

### ISSUE THREAD

**Issue by asp8200** [nf-core/sarek#835] opened 2022-11-14 15:31 UTC
### Description of the bug

The vcf-file from mpileup isn't getting annotated along with the other germline-vcfs. 

https://github.com/nf-core/sarek/blob/bcd7bf9cb98cddec27bb54fb47ee122c09388c02/workflows/sarek.nf#L984-L989

The command below resulted in vcf-files both from mpileup and strelka, but only an annotated vcf-file from strelka.

### Command used and terminal output

```console
nextflow run main.nf -profile test,singularity  --input tests/csv/3.0/mapped_joint_bam.csv --step variant_calling --tools mpileup,strelka,vep --skip_tools multiqc
```

**Comment by FriederikeHanssen** [comment] 2022-11-15 10:58
Since mpileup is so far not producing vcfs, this is expected. Should be addressed in #832

**Comment by asp8200** [comment] 2022-12-05 16:54
It was forgotten in #832

**Comment by FriederikeHanssen** [comment] 2023-03-21 13:02
Mpileup doesn't produce vcfs -> not annotated as intended. 
Can you mpileup even produce vcfs, if not then we don't need to do anything

**Comment by asp8200** [comment] 2023-03-21 13:13
On the dev-branch, the subworkflow `bam_variant_calling_germline_all` is returning a vcf from mpileup+bcftools:

https://github.com/nf-core/sarek/blob/d9675e6a1d24892a7b9e1cb211be137154795504/subworkflows/local/bam_variant_calling_germline_all/main.nf#L60

To fix this issue just at the mpileup-vcf-file to the files getting annotated in `sarek.nf`.

**Closed** 2023-06-15 10:05 UTC
Labels: enhancement, help wanted
