### ISSUE TITLE
GatherPileupSummaries in wgs mode failing because of sample mix-up

### ISSUE THREAD

**Issue by daisymut** [nf-core/sarek#818] opened 2022-11-08 16:00 UTC
### Description of the bug

I was running sarek with mutect2 on a group of control samples using a custom config file as first step of PON generation. The same command was successful on a selected list of genes using a small bed file and the --wes parameter: 

`nextflow run nf-core/sarek -r 3.0.2 -profile ibiss -c mutect2.pon.config --igenomes_base $refdir --input $ponssf --wes --intervals $tbed --step variant_calling --tools mutect2 --outdir ${pondir}/poncalls_nomnp --pon false `

I then ran it using the command below and the pipeline exited with error because in the GatherPileupSummaries  step of sample p28 there was one file from another sample:
`p92.mutect2.chr2_94140558-94293015.pileups.table`
I verified that in the process folder /lustre/home/mmutarelli/project_prostate/sammy/pon/work/60/297638c50dc710ce33f8b9a4c64b29 there was a soft link of this file among the correct ones 

### Command used and terminal output

```console
$nextflow run nf-core/sarek -r 3.0.2 -profile ibiss -c mutect2.pon.config --igenomes_base /lustre/home/mmutarelli/references --input /lustre/home/mmutarelli/project_prostate/sammy/pon/normals_for_pon.csv --step variant_calling --tools mutect2 --outdir /lustre/home/mmutarelli/project_prostate/sammy/pon/prostate_ctrl_pon_calls --pon false


-[nf-core/sarek] Pipeline completed with errors-
Error executing process > 'NFCORE_SAREK:SAREK:TUMOR_ONLY_VARIANT_CALLING:GATK_TUMOR_ONLY_SOMATIC_VARIANT_CALLING:GATHERPILEUPSUMMARIES (p28)'

Caused by:
  Process `NFCORE_SAREK:SAREK:TUMOR_ONLY_VARIANT_CALLING:GATK_TUMOR_ONLY_SOMATIC_VARIANT_CALLING:GATHERPILEUPSUMMARIES (p28)` terminated with an error exit status (2)

Command executed:

  gatk --java-options "-Xmx12g" GatherPileupSummaries \
      --I p28.mutect2.chr2_97489619-238903659.pileups.table --I p28.mutect2.chr4_58921382-190123121.pileups.table --I p28.mutect2.chr3_93705575-198235559.pileups.table --I p28.mutect2.chr12
_37257056-37379851.pileups.table --I p28.mutect2.chr1_29553836-121976459.pileups.table --I p28.mutect2.chr3_10001-90565295.pileups.table --I p28.mutect2.chr14_19611714-106883718.pileups.tab
le --I p28.mutect2.chr5_50109808-139452659.pileups.table --I p28.mutect2.chr7_61967064-61976104.pileups.table --I p28.mutect2.chr1_143184588-223558935.pileups.table --I p28.mutect2.chr10_47
870369-124121200.pileups.table --I p28.mutect2.chr6_95070791-167591393.pileups.table --I p28.mutect2.chr13_18408107-86202979.pileups.table --I p28.mutect2.chr9_68220553-134183092.pileups.ta
ble --I p28.mutect2.chr15_23276875-84270066.pileups.table --I p28.mutect2.chr6_60001-58453888.pileups.table --I p28.mutect2.chr7_240243-58119653.pileups.table --I p28.mutect2.chr8_85714223-
145078636.pileups.table --I p28.mutect2.chr2_32917626-89330679.pileups.table --I p28.mutect2.chr17_26820267-26859724.pileups.table --I p28.mutect2.chrX_62462543-114281198.pileups.table --I
p28.mutect2.chr11_60001-50821348.pileups.table --I p28.mutect2.chr11_88002897-135076622.pileups.table --I p28.mutect2.chr16_46380683-90228345.pileups.table --I p28.mutect2.chr9_10001-412259
86.pileups.table --I p28.mutect2.chr8_45927266-85664222.pileups.table --I p28.mutect2.chr10_10001-38529907.pileups.table --I p28.mutect2.chrX_2132995-37099262.pileups.table --I p28.mutect2.
chr6_61371373-95020790.pileups.table --I p28.mutect2.chr22_18339130-18433513.pileups.table --I p28.mutect2.chr8_12284346-43983744.pileups.table --I p28.mutect2.chr19_27240875-58607616.pileu
ps.table --I p28.mutect2.chr21_10269869-10274327.pileups.table --I p28.mutect2.chr5_17580549-46435900.pileups.table --I p28.mutect2.chr20_36314720-64334167.pileups.table --I p28.mutect2.chr
12_7084651-34719407.pileups.table --I p28.mutect2.chr20_63841-26364240.pileups.table --I p28.mutect2.chr18_20571467-20830724.pileups.table --I p28.mutect2.chr18_54537529-80263285.pileups.ta
ble --I p28.mutect2.chr5_155761325-181478259.pileups.table --I p28.mutect2.chr13_86252980-111703855.pileups.table --I p28.mutect2.chr19_60001-24448980.pileups.table --I p28.mutect2.chrX_120
929382-144425606.pileups.table --I p28.mutect2.chr4_8816478-9272916.pileups.table --I p28.mutect2.chr17_491112-21795850.pileups.table --I p28.mutect2.chr1_228608365-248946422.pileups.table
--I p28.mutect2.chr16_10001-18436486.pileups.table --I p28.mutect2.chr15_84320067-101981189.pileups.table --I p28.mutect2.chr5_10001-17530548.pileups.table --I p28.mutect2.chr11_71055697-87
978202.pileups.table --I p28.mutect2.chr2_16146120-32867130.pileups.table --I p28.mutect2.chr4_32839017-49336924.pileups.table --I p28.mutect2.chr11_54525075-70955696.pileups.table --I p28.
mutect2.chr5_139453660-155760324.pileups.table --I p28.mutect2.chr2_10001-16145119.pileups.table --I p28.mutect2.chr18_10001-15410899.pileups.table --I p28.mutect2.chr7_143700805-159335973.
pileups.table --I p28.mutect2.chr16_18486487-33214595.pileups.table --I p28.mutect2.chr1_16849164-29552233.pileups.table --I p28.mutect2.chrX_37285838-49348394.pileups.table --I p28.mutect2
.chrX_144475607-156030895.pileups.table --I p28.mutect2.chr1_2746291-12954384.pileups.table --I p28.mutect2.chr10_124121503-133690466.pileups.table --I p28.mutect2.chrY_11642903-11647442.pi
leups.table --I p28.mutect2.chrX_50278965-58555579.pileups.table --I p28.mutect2.chr8_60001-7617127.pileups.table --I p28.mutect2.chr18_47019913-54536574.pileups.table --I p28.mutect2.chr4_
1441553-8797477.pileups.table --I p28.mutect2.chr4_51793952-58878793.pileups.table --I p28.mutect2.chr12_10001-7083650.pileups.table --I p28.mutect2.chrY_2781480-9046914.pileups.table --I p
28.mutect2.chr10_41693522-41916265.pileups.table --I p28.mutect2.chr20_30811899-31001508.pileups.table --I p28.mutect2.chrY_21805282-26673214.pileups.table --I p28.mutect2.chr1_223608936-22
8558364.pileups.table --I p28.mutect2.chr18_15791048-20564714.pileups.table --I p28.mutect2.chr8_7667128-12234345.pileups.table --I p28.mutect2.chrX_116595567-120879381.pileups.table --I p2
8.mutect2.chr9_134185537-138334717.pileups.table --I p28.mutect2.chr17_22813680-26627010.pileups.table --I p28.mutect2.chrX_58605580-62412542.pileups.table --I p28.mutect2.chr1_13004385-167
99163.pileups.table --I p28.mutect2.chr21_43262463-46699983.pileups.table --I p28.mutect2.chr11_51078349-54425074.pileups.table --I p28.mutect2.chr2_94140558-94293015.pileups.table --I p92.
mutect2.chr2_94140558-94293015.pileups.table --I p28.mutect2.chr1_10001-207666.pileups.table --I p28.mutect2.chr12_34829238-37185252.pileups.table --I p28.mutect2.chr9_43282957-43332174.pil
eups.table --I p28.mutect2.chr4_49708101-51743951.pileups.table --I p28.mutect2.chr16_36260629-36261158.pileups.table --I p28.mutect2.chr22_16302844-16304296.pileups.table --I p28.mutect2.c
hr10_39686683-41593521.pileups.table --I p28.mutect2.chr20_26596364-28499358.pileups.table --I p28.mutect2.chr2_92188146-94090557.pileups.table --I p28.mutect2.chr16_34339330-34521510.pileu
ps.table --I p28.mutect2.chr8_44033745-45877265.pileups.table --I p28.mutect2.chr13_111843442-113673020.pileups.table --I p28.mutect2.chrX_222347-1949345.pileups.table --I p28.mutect2.chrY_
20257794-21739542.pileups.table --I p28.mutect2.chr22_12488691-12641730.pileups.table --I p28.mutect2.chr9_66591388-67920552.pileups.table --I p28.mutect2.chr14_16054460-16061677.pileups.ta
ble --I p28.mutect2.chr9_65048125-65080082.pileups.table --I p28.mutect2.chrY_10316945-10544039.pileups.table --I p28.mutect2.chr21_8756716-8886604.pileups.table --I p28.mutect2.chr9_615188
09-61735368.pileups.table --I p28.mutect2.chr15_21242091-21778502.pileups.table --I p28.mutect2.chr4_31832570-32833016.pileups.table --I p28.mutect2.chr7_60878235-61327788.pileups.table --I
 p28.mutect2.chr9_62798833-62958371.pileups.table --I p28.mutect2.chr9_63968448-64135013.pileups.table --I p28.mutect2.chr15_22358243-23226874.pileups.table --I p28.mutect2.chr16_33442412-3
4289329.pileups.table --I p28.mutect2.chrY_9453714-10266944.pileups.table --I p28.mutect2.chr20_29271827-29315342.pileups.table --I p28.mutect2.chr21_7743701-7865746.pileups.table --I p28.mutect2.chr22_11428057-11497337.pileups.table --I p28.mutect2.chr9_60518559-60688432.pileups.table --I p28.mutect2.chr20_28504765-28751119.pileups.table --I p28.mutect2.chr21_6789086-6934219.pileups.table --I p28.mutect2.chrX_49528395-50228964.pileups.table --I p28.mutect2.chr13_113723021-114354328.pileups.table --I p28.mutect2.chr20_30088349-30425128.pileups.table \
      --O p28.mutect2.pileupsummaries.table \
      --sequence-dictionary Homo_sapiens_assembly38.dict \
      --tmp-dir . \


  Runtime.totalMemory()=9401532416
  ***********************************************************************

  A USER ERROR has occurred: Bad input: Combining PileupSummaryTables from different samples is not supported. Got samples p28_p28 and p92_p92

  ***********************************************************************
  Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.

Work dir:
  /lustre/home/mmutarelli/project_prostate/sammy/pon/work/60/297638c50dc710ce33f8b9a4c64b29

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Relevant files

[.nextflow.log](https://github.com/nf-core/sarek/files/9962869/i.nextflow.log)

### System information

- Nextflow version 21.10.6 build 5660
- Hardware HPC
- Executor slurm
- Container engine: Singularity
- OS Linux CentosOS 7
- Version of nf-core/sarek 3.0.2

**Comment by FriederikeHanssen** [comment] 2022-12-09 10:06
#888 attempted fix here

**Comment by maxulysse** [comment] 2023-01-18 10:53
#896 should definitively fix that

**Comment by maxulysse** [comment] 2023-02-01 10:59
@daisymut I'm closing the issue since #896 should have provided a fix.
Please open it again if you see that the issue is still there

**Closed by maxulysse** 2023-02-01 10:59 UTC
Labels: bug
