### ISSUE TITLE
Control-FREEC *.png output files don't show text

### ISSUE THREAD

**Issue by mauro-saporita** [nf-core/sarek#921] opened 2023-01-25 12:53 UTC
### Description of the bug

CONTROLFREEC_MAKEGRAPH generates tree *.png files as expected but those plots don't contain text instead there are some white little boxes (see image attached).

Biocontainer used: quay.io/biocontainers/control-freec:11.6--h1b792b2_1

<img width="727" alt="Screenshot 2023-01-25 at 13 13 26" src="https://user-images.githubusercontent.com/64437596/214567909-98ee9b29-62f4-426d-a418-98c2962355a0.png">

### System information

Sarek version 3.1.2
Biocontainer used: quay.io/biocontainers/control-freec:11.6--h1b792b2_1

**Comment by maxulysse** [comment] 2023-01-25 13:06
Hi @mauro-saporita thanks for reporting this issue, we will investigate

**Comment by maxulysse** [comment] 2023-02-02 11:17
Results from the AWS megatests: https://nf-co.re/sarek/results#sarek/results-c87f4eb694a7183e4f99c70fca0f1d4e91750b33/somatic_test/variant_calling/controlfreec/HCC1395T_vs_HCC1395N/HCC1395T_vs_HCC1395N_BAF.png

So definitively we can reproduce.
Thanks @apeltzer

**Comment by nschcolnicov** [comment] 2023-09-15 16:01
Hi @FriederikeHanssen! I have been looking into this issue, since I was struggling with it too. In my case **I couldn't reproduce it using the Biocontainer "quay.io/biocontainers/control-freec:11.6--h1b792b2_1" image**. This image seems to be working fine in regards of the plots text.
Instead I saw that I had **this issue only when using the image: 'https://depot.galaxyproject.org/singularity/control-freec:11.6--h1b792b2_1'**

I looked into the containers, and comparing the one from biocontainer and the one from galaxyproject, if I run the command "fc-list" I don't get any results in the latter one, while I do get the full list of fonts in the biocontainer one 

@mauro-saporita is it possible that the image that was selected when running the module was the one from galaxyproject instead of the biocontainer one? Do you by any chance still have the log or the command used? 

**PROPOSED SOLUTION**
R looks for the fonts in the following paths:  /usr/share/fonts, /usr/local/share/fonts, ~/.fonts, ~/.local/share/fonts, and their subdirectories.
[link to document](https://search.r-project.org/CRAN/refmans/sysfonts/html/font_paths.html#:~:text=Default%20search%20paths%20will%20be,%2Fshare%2Ffonts%20%2C%20~%2F.)

In order to fix this issue, the image in galaxyproject should be updated to include the font files in the path /usr/local/fonts, which is the same one that is used in the biocontainer image. I'm attaching the full list of fonts included in the working biocontainer image, in case it might help: 
[fontList.txt](https://github.com/nf-core/sarek/files/12621351/fontList.txt)

**Comment by FriederikeHanssen** [comment] 2023-09-16 20:11
Hey! Thanks a lot for investigating. Coincidentally, i just updated the container in the modules repo today (https://github.com/nf-core/modules/pull/3843)  and it seems it was fixed with the latest release. This is an image generated with singularity on 11.6b 
![test_ratio](https://github.com/nf-core/sarek/assets/12273093/5ca61484-a811-467e-a9e0-a1eafe7723de)


In the PR you can also see two images one generated with Docker and one with Singularity

**Comment by nschcolnicov** [comment] 2023-09-21 12:21
@FriederikeHanssen Thank you! Running it with the new container fixed the issue for me

**Closed** 2024-08-19 13:16 UTC
Labels: bug, help wanted
