### ISSUE TITLE
[BUG] ControlFreec issues with targeted sequencing data

### ISSUE THREAD

**Issue by apeltzer** [nf-core/sarek#670] opened 2022-07-20 11:22 UTC
## Description of the bug

Running Sarek with `-r dev` and using a capture / targeted BED runs into trouble with ControlFreec. 

https://github.com/BoevaLab/FREEC/issues/106 for more context, @FriederikeHanssen knows about it ;-) 

## Expected behaviour

ControlFreec just running through

## Log files

```console
Error: chromosome HLA-DRB1*16:02:01 present in your /foo/bar/baz/Homo_sapiens_assembly38.fasta.fai file was not detected in your file with capture regions wgs_calling_regions.hg38.bed
  Please solve this issue and rerun Control-FREEC
```

@[chernomor](https://github.com/OlgaChern) reported it to me at BI, now reporting here so that @FriederikeHanssen has an issue

**Comment by FriederikeHanssen** [comment] 2022-07-20 11:25
Thank you! I'll try to think of a temporary work around

**Comment by FriederikeHanssen** [comment] 2022-09-07 15:04
I have added a patchy workaround in #728 . It will be part of release 3.0.2, hopefully by the end of the week. A length file containing only the relevant regions can be supplied with `--cf_chrom_len` . 

I would close this issue, since I still have the one open in the controlfreec repository to hopefully get notified if anything changes upstream.

Let me know, if you run into any more issues regarding this!

**Closed by FriederikeHanssen** 2022-09-07 15:04 UTC
Labels: bug

**Comment by chumawinnie** [comment] 2024-09-16 09:55
### Issue with Control-FREEC in Sarek 3.4.3: Unable to Extract Reads from Tumour_vs_Normal.tumor.mpileup.gz

**Description:**

I encountered an issue while running the Sarek 3.4.3 pipeline with Control-FREEC as one of the tools. Specifically, Control-FREEC fails to extract reads from `Tumour_vs_Normal.tumor.mpileup.gz`, resulting in zero reads being used for the copy number profile. 

The command I used is as follows:

```
nextflow run nf-core/sarek -r 3.4.3 -profile docker \
  --input /home/obiorach/test-work-sarek/tiny-test_metadata.csv \
  --outdir /home/obiorach/test-work-sarek/tiny-data-output \
  --genome GATK.GRCh38 \
  --tools mutect2,strelka,vep,manta,tiddit,cnvkit,controlfreec,msisensorpro \
  --max_cpus 20 \
  --max_memory '30 GB' \
  -c custom.config \
  --vep_species homo_sapiens \
  --vep_cache_version 111 \
  --igenomes_base 's3://ngi-igenomes/igenomes' \
  -resume
```

**Command Output and Error:**

```
Control-FREEC v11.6 : a method for automatic detection of copy number alterations, subclones, and for accurate estimation of contamination and main ploidy using deep-sequencing data.
Multi-threading mode using 2 threads
..consider the sample being female
..Breakpoint threshold for segmentation of copy number profiles is 0.8
..telocenromeric set to 50000
..FREEC is not going to adjust profiles for a possible contamination by normal cells
..Coefficient Of Variation set equal to 0.05
..it will be used to evaluate window size
..Output directory: .
..Directory with files containing chromosome sequences: Chromosomes
..Sample file: Tumour_vs_Normal.tumor.mpileup.gz
..Sample input format: pileup
..Control file: Tumour_vs_Normal.normal.mpileup.gz
..Input format for the control file: pileup
..minimal expected GC-content (general parameter "minExpectedGC") was set to 0.35
..maximal expected GC-content (general parameter "maxExpectedGC") was set to 0.55
..Polynomial degree for "ReadCount ~ GC-content" normalization is 3 or 4: will try both
..Minimal CNA length (in windows) is 1
..File with chromosome lengths: Homo_sapiens_assembly38.len
..Using the default minimal mappability value of 0.85
..Mappability fileout100m2_hg38.gem be used: all low mappability positions will be discarded
..uniqueMatch = FALSE
..average ploidy set to 2
..break-point type set to 2
..noisyData set to 0
..minimal number of reads per window in the control sample is set to 10
..Control-FREEC will look for subclones present in at least 20% of cell population
..will use SNP positions from dbsnp_146.hg38.vcf.gz to calculate BAF profiles
..Starting reading dbsnp_146.hg38.vcf.gz to get SNP positions
..read 139547806 SNP positions
..use "pileup" format of reads to calculate BAF profiles
..Starting reading Tumour_vs_Normal.tumor.mpileup.gz to calculate BAF profiles
..use "pileup" format of reads to calculate BAF profiles
..Starting reading Tumour_vs_Normal.normal.mpileup.gz to calculate BAF profiles
0 lines read
0 lines read
..File Homo_sapiens_assembly38.len was read
  total genome size: 3.08827e+09
  read number: 0
  coefficientOfVariation: 0.05
  evaluated window size: -2147483648
..[genomecopynumber] Starting reading Tumour_vs_Normal.tumor.mpileup.gz
..finished reading Tumour_vs_Normal.tumor.mpileup.gz
0 lines read..
0 reads used to compute copy number profile
```

**Error:**

```
Error: FREEC was not able to extract reads from Tumour_vs_Normal.tumor.mpileup.gz
Check your parameters: inputFormat and mateOrientation
Use "matesOrientation=0" if you have single end reads
Check the list of possible input formats at: 
http://bioinfo-out.curie.fr/projects/freec/tutorial.html#CONFIG
```

**Work Directory:**
```
/home/obiorach/test-work-sarek/work/2d/33a3095cd4357f67c1284974bed224
```

**Additional Details:**
- Control-FREEC version: 11.6
- Sarek version: 3.4.3
- Genome: GATK.GRCh38
- Input formats: Tumour and Normal mpileup files
- The mpileup files used in this pipeline appear to contain no lines (0 lines read).

It appears that Control-FREEC is not extracting any reads from the provided mpileup files, which might indicate a problem with the input format, mate orientation, or file compatibility with Control-FREEC. I have followed the configuration instructions, but the issue persists.

Could you please help identify the cause of this problem or provide guidance on adjusting the input format and configuration for Control-FREEC in this context?

Thank you!
