### ISSUE TITLE
Consider adding SmuRF for Random Forest Ensembl Somatic Calling

### ISSUE THREAD

**Issue by apeltzer** [nf-core/sarek#933] opened 2023-02-02 13:06 UTC
### Description of feature

https://github.com/skandlab/SMuRF#input-alt

(most callers there, needs just varscan + one more I think)

**Comment by maxulysse** [comment] 2023-02-02 13:21
duplicate of #95

**Closed by maxulysse** 2023-02-02 13:21 UTC
Labels: enhancement

**Comment by apeltzer** [comment] 2023-02-02 15:03
Thanks @maxulysse ;-)
